version: '3'
services:
  electrum:
    image: ncdns
    container_name: ncdns
    ports:
      - 127.0.0.1:53535:53535/udp
    environment:
      - ELECTRUM_USER=electrum
      - ELECTRUM_PASSWORD=electrumz
      - TESTNET="False"
    volumes:
      - ./config/electrum-nmc:/data/electrum-nmc
